#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run format

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. 🤢🤮🤢🤮';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check.'
    false;
)


# If everything passes... Now we can commit
echo 'Everything Looks Good. Commiting Changes 😀✅'
